apiVersion: v1
kind: Service
metadata:
  name: nogate
  namespace: devnoops
  labels:
    app: nogate
    platform: devnoops
spec:
  type: ClusterIP
  selector:
    app: nogate
  ports:
    - port: 9095
      targetPort: 9095
      protocol: TCP
      name: http
