apiVersion: v1
kind: Service
metadata:
  name: noeditor
  namespace: devnoops
  labels:
    app: noeditor
    platform: devnoops
spec:
  type: ClusterIP
  selector:
    app: noeditor
  ports:
    - port: 9098
      targetPort: 9098
      protocol: TCP
      name: http
