apiVersion: v1
kind: Service
metadata:
  name: nospace
  namespace: devnoops
  labels:
    app: nospace
    platform: devnoops
spec:
  type: ClusterIP
  selector:
    app: nospace
  ports:
    - port: 9101
      targetPort: 9101
      protocol: TCP
      name: http
