apiVersion: v1
kind: Service
metadata:
  name: nogit
  namespace: devnoops
  labels:
    app: nogit
    platform: devnoops
spec:
  type: ClusterIP
  selector:
    app: nogit
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
