apiVersion: apps/v1
kind: Deployment
metadata:
  name: nobill
  namespace: devnoops
  labels:
    app: nobill
    platform: devnoops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nobill
  template:
    metadata:
      labels:
        app: nobill
        platform: devnoops
    spec:
      containers:
        - name: nobill
          image: localhost:30003/devnoops/nobill:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9103
              protocol: TCP
          env:
            - name: PORT
              value: "9103"
            - name: POSTGRES_HOST
              value: "postgresql.postgres.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "devnoops"
            - name: POSTGRES_PASSWORD
              value: "devnoops-pg-pass"
            - name: POSTGRES_DB
              value: "devnoops"
            - name: REDIS_ADDR
              value: "redis-master.redis.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              value: "devnoops-redis-pass"
            - name: NATS_URL
              value: "nats://nats.nats.svc.cluster.local:4222"
            - name: MINIO_ENDPOINT
              value: "minio.minio.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              value: "devnoops-minio"
            - name: MINIO_SECRET_KEY
              value: "devnoops-minio-secret"
            - name: MINIO_USE_SSL
              value: "false"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9103
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9103
            initialDelaySeconds: 5
            periodSeconds: 10
